name: Install Dependencies
description: Sets up Bun, then installs all dependencies

runs:
  using: composite
  steps:
    - name: Install Node.js
      uses: actions/setup-node@v5
      with:
        node-version: lts/krypton

    - name: Install bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version-file: '.bun-version'

    - name: Install dependencies
      shell: bash
      run: bun ci
